version: "3.9"

volumes:
  prakticum_postgres_volume: ~

networks:
  prakticum_network:
    external: true

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            target: front
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        networks:
          - prakticum_network
        ports:
            - "${CLIENT_PORT}:80"
        environment:
          - CLIENT_PORT=${CLIENT_PORT}
          - SERVER_PORT=${SERVER_PORT}

    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            target: back
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        networks:
          - prakticum_network
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
          SERVER_PORT: ${SERVER_PORT}

    postgres:
      container_name: prakticum-postgres
      image: postgres:14
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - prakticum_postgres_volume:/var/lib/postgresql/data
      networks:
        - prakticum_network
